<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '5a47fca7078b843bbc46ff49eacd546d',
  'DATABASE_URL' => 'mysql://root:User1234@localhost:3306/all2you_local',
  'MAILER_URL' => 'null://localhost',
);
