<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '5a47fca7078b843bbc46ff49eacd546d',
  'DATABASE_URL' => 'mysql://u0441585_default:EWf3!uWd@127.0.0.1:3306/u0441585_gift',
  'MAILER_URL' => 'smtp://server195.hosting.reg.ru:465?encryption=ssl&auth_mode=login&username=info@gift.all2you.ru&password=sophia1953',
);
